flask_app/main/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, PasswordField, FileField, FormField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from ...model.user import User
from wtforms import ValidationError


class EmailForm(FlaskForm):
    email = StringField('what is your email?', validators=[DataRequired()])
    # password = PasswordField('what is your password?', validators=[DataRequired()])
    submit = SubmitField('send mail')
    # logout = SubmitField('logout')


class LoginForm(FlaskForm):

    username = StringField('username: ', validators=[DataRequired()])
    password = PasswordField('password: ', validators=[DataRequired()])
    remember_me = BooleanField('remember me')
    # email = SubmitField('forget password')
    submit = SubmitField('Login')


class RegisterForm(FlaskForm):

    email = StringField('email_addr: ',
                        validators=[DataRequired(), Length(1, 64), Email()])

    username = StringField('username: ',
                           validators=[DataRequired(), Length(1, 64),
                            Regexp('^[A-Za-z][A-Za-z0-9_. ]*$', 0,
                                    '用户名要以字母开头！')])

    password = PasswordField('password: ',
                           validators=[DataRequired(),
                                       EqualTo('comfirm_password', message='密码输入不一致！')])
    comfirm_password = PasswordField('comfirm: ', validators=[DataRequired()])
    submit = SubmitField('Register')


class EditForm(FlaskForm):
    real_name = StringField('realname: ', validators=[DataRequired()])
    phone = StringField('phone: ', validators=[DataRequired()])
    username = StringField('username: ', validators=[Length(1, 64)])
    email = StringField('email: ', validators=[Length(1, 64)])
    location = StringField('address: ', validators=[Length(1, 64)])
    submit = SubmitField('Modify')


class ProfileForm(FlaskForm):
    profile_picture = FileField('profile picture: ', validators=[DataRequired()])
    submit = SubmitField('Submit')


class PasswordForm(FlaskForm):
    password = PasswordField('new password', validators=[DataRequired()])
    comfirmd = PasswordField('comfirm password',
                             validators=[DataRequired(),
                                         EqualTo('password', message='密码输入不一致！')])

    submit = SubmitField('submit')





def validate_email(self, field):
    if User.query.filter_by(email=field.data).first():
        raise ValidationError('Email already registered.')


def validate_username(self, field):
    if User.query.filter_by(username=field.data).first():
        raise ValidationError('Username already in use.')

flask_app/__init__.py
from flask import Flask, url_for
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager, current_user
from flask_admin import Admin, BaseView, expose, form

import os.path as op

file_path = op.join(op.dirname(__file__), 'static')

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'users.login'

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
admin = Admin(name=u'鑫与汇后台', template_mode='bootstrap2')


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    admin.init_app(app)
    login_manager.init_app(app)
    # 附加路由和自定义的错误页面
    from flask_app.main import main as main_blueprint
    from flask_app.main.user import user as user_blueprint
    from flask_app.main.car import car as car_blueprint
    from flask_app.api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(user_blueprint)
    app.register_blueprint(car_blueprint)
    app.register_blueprint(api_1_0_blueprint)  #url_prefix='/api/v1.0'
    return app

flask_app/api_1_0/__init__.py
from flask import Blueprint
api = Blueprint('api', __name__, url_prefix='/api/v1.0')
from . import authentication, cars, users, errors

flask_app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors

flask_app/main/car/__init__.py
from flask import Blueprint
car = Blueprint('car', __name__, url_prefix='/car')
from . import views, errors

flask_app/main/car/views.py
from flask import request
# from flask import current_app
from flask import render_template
from . import car
from flask_script import Manager, Server
# from .forms import LoginForm, RegisterForm


@car.route('/')
def index():
    return render_template('index.html')


@car.route('/proinfo/')
def proinfo():
    return render_template('car/proinfo.html')


@car.route('/recommend/')
def recommend():
    return render_template('car/recommend.html')


@car.route('/select/')
def select():
    return render_template('car/select.html')


@car.route('/service/')
def service():
    return render_template('car/service.html')


@car.route('/business/')
def business():
    return render_template('car/business.html')


@car.route('/job/')
def job():
    return render_template('car/job.html')


@car.route('/contact/')
def contact():
    return render_template('car/contact.html')

flask_app/main/user/__init__.py
from flask import Blueprint
user = Blueprint('users', __name__, url_prefix='/user')
from . import views, errors

flask_app/main/user/views.py
from flask import request, flash, redirect, url_for
from flask import render_template, abort, current_app
from . import user
from flask_script import Manager, Server
from .forms import LoginForm, RegisterForm, EditForm, ProfileForm, EmailForm, PasswordForm
from ...model.user import User
from flask_login import login_user, login_required, logout_user, login_required, current_user
from flask_app import db, file_path, mk_nail
from flask_mail import Message
from flask_app import mail
from flask_app import config
from flask_app.email import send_email
import os
from flask_admin import form as fo_ad
from flask_app.model.car import CarParm, CarDetail, CarImage, CarModel


@user.route('/')
def index():
    user = User.query.filter_by(id=106).first()
    user.password = '123'
    # print('**************************')
    # print(CarDetail.query.filter_by(id=1).first().model)
    # User.generate_fake(100)
    return render_template('index.html')


@user.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.ping()
        if not current_user.is_administrator and request.endpoint == 'users.userlist':
        #     return redirect(url_for('user.userlist'))
        # else:
            abort(400)
    # else:
    #     abort(400)



@user.route('/login/', methods=('GET', 'POST'))
def login():
    name = None
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('users.index'))
        flash('Invalid username or password.')
    return render_template('login.html', form=form, name=name)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('users.login'))


@user.route('/register/', methods=('GET', 'POST'))
def register():
    if current_user.is_authenticated:
        logout_user()
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()

        token = user.generate_confirmation_token()
        # send_email(to=user.email, subject='Hello Flask',
        #            template='user/welcome', user_obj=user, token=token)
        flash('You can now login.')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)



@user.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('users.index'))

    if current_user.confirm(token):
        flash('You have confirmed your account. Thanks!')
    else:
        flash('The confirmation link is invalid or has expired.')
    return redirect(url_for('main.index'))


@user.route('/confirm')
@login_required
def reconfirm():
    token = current_user.generate_confirmation_token()
    send_email(to=current_user.email, subject='Hello Flask',
               template='user/welcome', user_obj=current_user, token=token)
    return redirect(url_for('.userinfo'))


@user.route('/userinfo/')
@login_required
def userinfo():

    return render_template('user/userinfo.html')


@user.route('/edit/', methods=('GET', 'POST'))
@login_required
def edit():
    form = EditForm()
    if form.validate_on_submit():
        current_user.real_name = form.real_name.data
        current_user.phone = form.phone.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.location = form.location.data

        # db.session.add(current_user)

        return redirect(url_for('.userinfo', username=current_user.username))
    form.real_name.data = current_user.real_name
    form.phone.data = current_user.phone
    form.username.data = current_user.username
    form.email.data = current_user.email
    form.location.data = current_user.location
    return render_template('user/edit.html', form=form)


# 更换头像
@user.route('/pro_edit/', methods=('GET', 'POST'))
@login_required
def pro_edit():
    form = ProfileForm()

    if form.validate_on_submit():
        file = request.files['profile_picture']
        import shutil
        src_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file.filename)
        dst_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file.filename[:-4]+'_thumb.jpg')
        file.save(src_path)
        mk_nail.image_size_off(current_app.config['UPLOAD_FOLDER'], file.filename)
        current_user.profile_picture = 'save/'+file.filename
        return redirect(url_for('.userinfo'))
    return render_template('user/pro_edit.html', form=form)


@user.route('/userlist/')
@login_required
def userlist():
    page = request.args.get('page', 1, type=int)
    u_ob = User.query.order_by(User.last_seen.desc())
    pagination = u_ob.paginate(page=page, per_page=3, error_out=True)
    userlist = pagination.items
    # userlist = User.query.all()
    # print(userlist)
    # print(pagination)
    return render_template('user/userlist.html', userlist=userlist, pagination=pagination)


@user.route('/resetpwd/', methods=('GET', 'POST')   )
def resetpwd():
    if current_user.is_authenticated:
        token = current_user.generate_confirmation_token()
        send_email(to=current_user.email, subject='Hello Flask',
                   template='user/resetpwd', user_obj=current_user, token=token)
        return redirect(url_for('.login'))
    else:
        form = EmailForm()
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            print(user)
            token = user.generate_confirmation_token()
            send_email(to=user.email, subject='Hello Flask',
                       template='user/resetpwd', user_obj=user, token=token)
            return redirect(url_for('.login'))
        return render_template('user/email.html', form=form)


@user.route('/reset/<token>', methods=('GET', 'POST'))
def reset(token):
    email = request.args.get('email')
    user = User.query.filter_by(email=email).first()
    if user.confirm(token):
        form = PasswordForm()
        if form.validate_on_submit():
            user.password = form.password.data
            return redirect(url_for('.login'))
        return render_template('user/password.html', form=form)
    else:
        flash('The confirmation link is invalid or has expired.')
    return redirect(url_for('.login'))

flask_app/main/views.py
from flask import request
# from flask import current_app
from flask import render_template
from flask_app.main import main
from flask_script import Manager, Server
# from .forms import LoginForm, RegisterForm


@main.route('/')
def index():
    return render_template('index.html')
    # user_agent = request.headers.get('user-agent')
    # return '这是该网页的user agent：%s' % user_agent

flask_app/model/__init__.py
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user
from flask import abort


class BaseModelview(ModelView):

    def getinfo(self):
        return "this is another model"

    def is_accessible(self):
        if current_user.is_anonymous:
            abort(400)
        else:
            return current_user.is_administrator

flask_app/views.py
from flask import request
# from flask import current_app
from flask import render_template
from flask_app import app
from flask_script import Manager, Server

manager = Manager(app)

@app.route('/')
def index():
    return render_template('index.html')
    # user_agent = request.headers.get('user-agent')
    # return '这是该网页的user agent：%s' % user_agent


@app.route('/hello<name>/')
def hello(name):
    return '<h1>Hello %s!</h1>' % name


if __name__ == "__main__":
    manager.run()

flask_app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
        page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
        &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
                <li class="active">
                    <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                </li>
            {% endif %}
        {% else %}
            <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,
        page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
        &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
    {% extends "bootstrap/base.html" %}
    {% block title %}Flasky{% endblock %}
    {% block head %}
        {{ super() }}
    <link rel="stylesheet"
          href="https://bootswatch.com/4/sketchy/bootstrap.css">

    <style type="text/css">
        li{
            list-style: none;
        }

        body{
           font-size: 2rem; font-family: Cabin Sketch, cursive;
        }
        ul{margin:0; padding: 0;}
        #submit, .btn{
            background-color: #78C2AD;
            border-color: #78C2AD;
            font-family: "Montserrat", -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            color: #fff;
            cursor: pointer;
            display: inline-block;
            font-weight: 400;
            text-align: center;
            vertical-align: middle;
            user-select: none;
            padding: 0.375rem 0.75rem;
            font-size: 1rem;
            line-height: 1.5;
            margin-top: 45px;
            border-radius: 255px 25px 225px 25px/25px 225px 25px 255px;
    }
        .control-label{
            font-family: Cabin Sketch, cursive;
        }
        #remember_me:before{
            position: sticky;
        }
        #remember_me:after{
            position: relative;
        }

        a{
            text-decoration: none;
        }
    </style>
    {% endblock %}

    {% block navbar %}
    <div class="container-fluid">
        <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/" style="height: 100%; font-size: 2.5rem">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                    <!--<li class="nav-item active">-->
                        <!--<a class="nav-link" href="/user/edit">Edit<span class="sr-only">(current)</span></a>-->
                    <!--</li> &nbsp;&nbsp;&nbsp;&nbsp;-->
                    <li class="nav-item active">
                        <a class="nav-link" href="/user/register">Register<span class="sr-only">(current)</span></a>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;
                    <!--<li class="nav-item active">-->
                        <!--<a class="nav-link" href="/user/userinfo">Userinfo<span class="sr-only">(current)</span></a>-->
                    <!--</li>&nbsp;&nbsp;&nbsp;&nbsp;-->
                    {% if current_user.is_administrator %}
                        <li class="nav-item active">
                            <a class="nav-link" href="/user/userlist">User list<span class="sr-only">(current)</span></a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="/user/register">Register<span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}

            </ul>
            <ul class="navbar-nav navbar-right">
                <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="themes" aria-expanded="false">{{ current_user.username }} </a>
              <div class="dropdown-menu" aria-labelledby="themes">
                  {% if current_user.is_authenticated %}
                    <a class="dropdown-item" href="/user/userinfo">Userinfo<span class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="/user/edit">Edit<span class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{{ url_for('users.logout') }}">Sign Out</a>

                  {% else %}
                    <a href="{{ url_for('users.login') }}" class="nav-link">Sign In</a>
                  {% endif %}

              </div>
            </li>

            </ul>
        </div>


    </div>
    </div>
    {% endblock %}
    {% block content %}
    <div class="container-fluid">
        <div class="bs-docs-section clearfix">
            <div class="row">
                <div class="col-lg-10  offset-lg-1">{% block page_content %}{% endblock %}</div>
            </div>
        </div>

    </div>

{% endblock %}
</body>
</html>

flask_app/templates/car_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .top_li{
            float: left;
            color: white;
            margin-left: 10px;
            font-size: 14px;
            line-height: 40px;
        }
        .top_li a{
            color: white;
        }
        .top_li a:hover{
            color: darkred;
        }
    </style>
</head>
<body>
    {% block head %}
    <div class="heads">
     <div class="top">
         <ul>
             {% if current_user.is_authenticated %}
                <li class="top_li">
                    <a href="/user/edit">Edit<span class="sr-only">(current)</span></a>
                </li> &nbsp;&nbsp;&nbsp;&nbsp;
                <li class="top_li">
                    <a href="/user/register">Register<span class="sr-only">(current)</span></a>
                </li>&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="top_li">
                    <a href="/user/userinfo">Userinfo<span class="sr-only">(current)</span></a>
                </li>&nbsp;&nbsp;&nbsp;&nbsp;
                {% if current_user.is_administrator %}
                    <li class="top_li">
                        <a href="/user/userlist">User list<span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
            {% else %}
            <li class="top_li">
                <a href="/user/register">Register<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}

            {% if current_user.is_authenticated %}
                <li  class="top_li">
                    <a href="{{ url_for('users.logout') }}" >Sign Out</a>
                </li>
            {% else %}
                <li  class="top_li">
                    <a href="{{ url_for('users.login') }}">Sign In</a>
                </li>
            {% endif %}
            </ul>
      <span class="headerRight"><img src="/static/images/phone.png" width="273" height="19" /></span>
     </div><!--top/-->
    </div><!--heads/-->
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>
</html>

flask_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
    {% extends "base.html" %}
    {% import "bootstrap/wtf.html" as wtf %}
    {% block title %}Login{% endblock %}

    {% block page_content %}
        <div class="page-header">
            <h1>XinYuHui-login!</h1>
        </div>
        <div class="col-lg-4">
            <div class="bs-component">
            {{ wtf.quick_form(form) }}</div>
        </div>
    {% endblock %}
</body>
</html>

flask_app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
    {% extends "base.html" %}
    {% import "bootstrap/wtf.html" as wtf %}
    {% block title %}注册{% endblock %}
    {% block page_content %}
        <div class="page-header">
        <h1>Welcome to register!</h1>
        </div>
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    {% endblock %}
</body>
</html>